version: '3'

services:
  php:
    build: docker/php
    tty: true
    volumes:
      - ".:/var/www/html"
      - "~/.composer:/home/docker/.composer"
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_ERROR_REPORTING: 1
